"use client";
import {FormEvent,useEffect,useState} from "react";
import {api,analyzeProject,AIAnalysisResponse,CompareResult,ProjectReleaseOverview,multiRoutePlaywrightExportUrl,regressionExportUrl,Scan} from "../../../lib/api";

export default function ProjectPage({params}:{params:{id:string}}){
 const id=Number(params.id); const [scans,setScans]=useState<Scan[]>([]); const [blockOn,setBlockOn]=useState<"HIGH"|"CRITICAL">("CRITICAL"); const [maxRisk,setMaxRisk]=useState(100); const [requireAll,setRequireAll]=useState(true); const [overview,setOverview]=useState<ProjectReleaseOverview|null>(null); const [routes,setRoutes]=useState<string[]>([]); const [selectedRoute,setSelectedRoute]=useState(""); const [url,setUrl]=useState(""); const [discoveredRoutes,setDiscoveredRoutes]=useState<string[]>([]); const [discoveryUrl,setDiscoveryUrl]=useState(""); const [role,setRole]=useState<"baseline"|"current">("current"); const [comparison,setComparison]=useState<CompareResult|null>(null); const [ai,setAi]=useState<AIAnalysisResponse|null>(null); const [autoCompare,setAutoCompare]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const load=async()=>{try{const [projectData,scanData,routeData,overviewData]=await Promise.all([api.project(id),api.scans(id),api.routes(id),api.releaseOverview(id)]);setScans(scanData);setRoutes(routeData);setOverview(overviewData);setBlockOn(projectData.block_on);setMaxRisk(projectData.max_risk_score);setRequireAll(projectData.require_all_routes);setSelectedRoute(current=>current||routeData[0]||"")}catch(e){setError(String(e))}}; useEffect(()=>{load()},[id]);
 async function scan(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await api.scan(id,url,role,selectedRoute||undefined);await load();setUrl("");if(autoCompare&&role==="current"){setComparison(await api.compare(id,selectedRoute||undefined))}}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function discover(){setBusy(true);setError("");try{const result=await api.discoverRoutes(id,discoveryUrl||url,20);setDiscoveredRoutes(result.routes);setDiscoveryUrl(result.source_url)}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function savePolicy(){setBusy(true);setError("");try{await api.updateReleasePolicy(id,{block_on:blockOn,max_risk_score:maxRisk,require_all_routes:requireAll});setOverview(await api.releaseOverview(id))}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function runAI(){setBusy(true);setError("");try{setAi(await analyzeProject(id))}catch(e){setError("AI analysis requires baseline/current scans and configured LLM API.")}finally{setBusy(false)}}
 const rankedChanges=comparison?[...comparison.diff.changed].sort((a,b)=>b.risk_points-a.risk_points):[];
 const riskClass=(points:number)=>points>=10?"critical":points>=5?"high":points>0?"medium":"low";
 async function compare(){setBusy(true);setError("");try{setComparison(await api.compare(id,selectedRoute||undefined))}catch(e){setError("Create both baseline and current scans before comparing.")}finally{setBusy(false)}}
 return <main className="shell"><a className="back" href="/">← Projects</a><header><div><span className="eyebrow">PROJECT #{id}</span><h1>Release analysis</h1><p>Capture a baseline, scan the current UI, then compare observable changes.</p></div></header>
 {overview&&overview.routes.length>0&&<section className="panel"><div className="section-head"><div><span className="eyebrow">MULTI-PAGE RELEASE</span><h3>Project Release Overview</h3></div><div className={`score ${overview.overall_risk_level.toLowerCase()}`}>{overview.overall_risk_score}<small>/100</small></div></div><div className={`priority ${overview.gate_status==="BLOCKED"?"critical":overview.gate_status==="INCOMPLETE"?"medium":"low"}`}>RELEASE GATE · {overview.gate_status}</div><p>{overview.gate_reason}</p><p><b>{overview.overall_risk_level}</b> overall · {overview.comparable_routes} comparable routes{overview.incomplete_routes>0?` · ${overview.incomplete_routes} incomplete`:""}</p><div className="export-actions"><a href={multiRoutePlaywrightExportUrl(id)}>Export full Playwright suite</a></div><div className="metrics"><label>Block on <select value={blockOn} onChange={e=>setBlockOn(e.target.value as "HIGH"|"CRITICAL")}><option value="CRITICAL">Critical</option><option value="HIGH">High</option></select></label><label>Max risk <input type="number" min="0" max="100" value={maxRisk} onChange={e=>setMaxRisk(Number(e.target.value))}/></label><label className="toggle"><input type="checkbox" checked={requireAll} onChange={e=>setRequireAll(e.target.checked)}/><span>Require all routes</span></label><button type="button" className="secondary" onClick={savePolicy} disabled={busy}>Save policy</button></div><div className="table">{overview.routes.map(item=><button type="button" className="row" key={item.route} onClick={()=>{setSelectedRoute(item.route);setComparison(null);setAi(null);if(item.status==="READY"){api.compare(id,item.route).then(setComparison).catch(()=>{})}else{setRole(item.status==="MISSING_BASELINE"?"baseline":"current");const known=scans.find(scan=>scan.route===item.route);setUrl(known?.url||"")}}}><code>{item.route}</code>{item.comparable?<><span className={`priority ${item.risk_level?.toLowerCase()}`}>{item.risk_level} · {item.risk_score}/100</span><span>+{item.added_count} −{item.removed_count} △{item.changed_count}</span><span>{item.regression_tests_count} tests</span></>:<span className="muted">{item.status==="MISSING_BASELINE"?"Missing baseline · prepare scan":"Missing current · prepare scan"}</span>}</button>)}</div></section>}
 <div className="grid">
  <section className="panel"><h3>Discover routes</h3><label>Start URL<input type="url" placeholder="https://example.com" value={discoveryUrl} onChange={e=>setDiscoveryUrl(e.target.value)}/></label><button type="button" className="secondary" onClick={discover} disabled={busy||!(discoveryUrl||url)}>Discover routes</button>{discoveredRoutes.length>0&&<div className="table">{discoveredRoutes.map(route=><button type="button" className="row" key={route} onClick={()=>{setSelectedRoute(route);try{const base=new URL(discoveryUrl||url);setUrl(new URL(route,base.origin).toString())}catch{}}}><code>{route}</code><span className="muted">Prepare scan</span></button>)}</div>}</section>
  <section className="panel"><h3>Run scan</h3><form onSubmit={scan}><label>Target URL<input type="url" placeholder="https://example.com" value={url} onChange={e=>setUrl(e.target.value)} required/></label><label>Scan role<select value={role} onChange={e=>setRole(e.target.value as "baseline"|"current")}><option value="baseline">Baseline</option><option value="current">Current</option></select></label><label className="toggle"><input type="checkbox" checked={autoCompare} onChange={e=>setAutoCompare(e.target.checked)}/><span>Compare automatically after current scan</span></label><button disabled={busy}>{busy?"Running…":"Run scan"}</button></form></section>
  <section className="panel risk"><h3>Release Risk</h3>{routes.length>0&&<label>Route<select value={selectedRoute} onChange={e=>{setSelectedRoute(e.target.value);setComparison(null);setAi(null)}}>{routes.map(route=><option key={route} value={route}>{route}</option>)}</select></label>}{comparison?<><div className={`score ${comparison.risk.level.toLowerCase()}`}>{comparison.risk.score}<small>/100</small></div><b>{comparison.risk.level}</b><p>{comparison.risk.summary}</p><div className="metrics"><span>+ {comparison.diff.added.length} added</span><span>− {comparison.diff.removed.length} removed</span><span>△ {comparison.diff.changed.length} changed</span></div></>:<><div className="score empty">--</div><p className="muted">Compare baseline and current scans to calculate risk.</p></>}<button className="secondary" onClick={compare} disabled={busy}>Compare latest</button></section>
 </div>
 <section className="panel"><h3>Scan history</h3>{scans.length===0?<p className="muted">No scans yet.</p>:<div className="table">{scans.map(s=><div className="row" key={s.id}><span className={`badge ${s.role}`}>{s.role}</span><div><strong>{s.title||s.url}</strong><small>{s.url}</small></div><span>{s.total_testable_objects} objects</span><time>{new Date(s.created_at).toLocaleString()}</time></div>)}</div>}{error&&<p className="error">{error}</p>}</section>
 {comparison&&<section className="panel"><h3>Detected changes</h3><div className="metrics"><span>+ {comparison.diff.added.length} added</span><span>− {comparison.diff.removed.length} removed</span><span>△ {comparison.diff.changed.length} changed</span><span>✓ {comparison.diff.unchanged_count} unchanged</span></div>{comparison.diff.added.length+comparison.diff.removed.length+comparison.diff.changed.length===0?<p className="muted">No observable DOM changes between the selected baseline and current scan.</p>:<p>Deterministic DOM comparison completed. Risk scoring below is heuristic and based on change type and affected fields.</p>}</section>}\n {comparison&&(comparison.diff.changed.length>0||comparison.diff.added.length>0||comparison.diff.removed.length>0)&&<section className="panel changes"><h3>Change details</h3>{rankedChanges.map((change,index)=><details className={`change priority-${riskClass(change.risk_points)}`} key={change.fingerprint}><summary><div><span className="badge changed">#{index+1}</span><strong>{change.after.display_name||change.after.locator}</strong><span className={`priority ${riskClass(change.risk_points)}`}>{riskClass(change.risk_points)} priority</span></div><small>{change.changed_fields.join(", ")} · <b>+{change.risk_points} risk</b></small></summary><div className="field-list">{change.changed_fields.map(field=><div className="field-change" key={field}><code>{field} <b>+{change.field_risk_points[field]??0}</b></code><span className="before">{String(change.before[field]??"—")}</span><span>→</span><span className="after">{String(change.after[field]??"—")}</span></div>)}</div></details>)}{comparison.diff.removed.map((item,i)=><div className="change-static" key={`removed-${i}`}><span className="badge removed">removed</span><strong>{item.display_name||item.locator}</strong><code>{item.locator}</code></div>)}{comparison.diff.added.map((item,i)=><div className="change-static" key={`added-${i}`}><span className="badge added">added</span><strong>{item.display_name||item.locator}</strong><code>{item.locator}</code></div>)}</section>}
 {comparison&&comparison.regression_focus.length>0&&<section className="panel focus"><div className="section-head"><div><span className="eyebrow">DETERMINISTIC PRIORITIES</span><h3>Regression Focus</h3></div><small>No LLM required</small></div>{comparison.regression_focus.slice(0,8).map(item=><div className="focus-item" key={`${item.priority}-${item.locator}`}><span className={`priority ${item.severity.toLowerCase()}`}>#{item.priority} {item.severity}</span><div><strong>{item.target}</strong><code>{item.locator}</code><p>{item.reason}</p><small>{item.suggested_check}</small></div><b>+{item.risk_points}</b></div>)}</section>}
 {comparison&&comparison.regression_tests.length>0&&<section className="panel tests"><div className="section-head"><div><span className="eyebrow">GENERATED FROM OBSERVED CHANGES</span><h3>Regression Test Cases</h3></div><div className="export-actions"><a href={regressionExportUrl(id,"json",selectedRoute||undefined)}>JSON</a><a href={regressionExportUrl(id,"markdown",selectedRoute||undefined)}>Markdown</a><a href={regressionExportUrl(id,"playwright",selectedRoute||undefined)}>Playwright</a></div></div>{comparison.regression_tests.slice(0,8).map(test=><details className="test-case" key={test.id}><summary><div><code>{test.id}</code><strong>{test.title}</strong></div><span className={`priority ${test.severity.toLowerCase()}`}>{test.severity} · +{test.risk_points}</span></summary><div className="test-body"><small>Locator: <code>{test.locator}</code></small><h4>Preconditions</h4><ol>{test.preconditions.map((x,i)=><li key={i}>{x}</li>)}</ol><h4>Steps</h4><ol>{test.steps.map((x,i)=><li key={i}>{x}</li>)}</ol><h4>Expected results</h4><ol>{test.expected_results.map((x,i)=><li key={i}>{x}</li>)}</ol><p className="model-note">Source: deterministic rules · no LLM</p></div></details>)}</section>}
 {comparison&&<section className="panel ai-panel"><div className="section-head"><div><span className="eyebrow">GROUNDED REASONING</span><h3>AI Release Analyst</h3></div><button onClick={runAI} disabled={busy}>{ai?"Re-run AI analysis":"Analyze with AI"}</button></div>{ai?<><p className="ai-summary">{ai.analysis.release_summary}</p><div className="ai-grid"><div><h4>Likely impact</h4>{ai.analysis.likely_impacts.map((x,i)=><p key={i}>• {x}</p>)}</div><div><h4>Regression focus</h4>{ai.analysis.regression_focus.map((x,i)=><p key={i}>• {x}</p>)}</div><div><h4>Suggested tests</h4>{ai.analysis.suggested_tests.map((x,i)=><p key={i}>• {x}</p>)}</div></div><div className="evidence"><h4>Evidence chain</h4>{[...ai.evidence.observed,...ai.evidence.retrieved].map(e=><details key={e.id}><summary><code>{e.id}</code> {e.kind==="observed"?"Observed fact":"Retrieved context"} {e.score!==null&&<small>score {e.score}</small>}</summary><p>{e.statement}</p><small>Source: {e.source}</small></details>)}</div><p className="model-note">Provider: {ai.provider} · Model: {ai.model} · Confidence: {ai.analysis.confidence}</p></>:<p className="muted">Run grounded AI reasoning over the deterministic diff and retrieved project context.</p>}</section>}
 {comparison&&comparison.risk.factors.length>0&&<section className="panel"><h3>Why this score?</h3>{comparison.risk.factors.map(f=><div className="factor" key={f.code}><div><strong>{f.description}</strong><small>{f.count} × {f.weight} points</small></div><b>+{f.points}</b></div>)}</section>}
 </main>
}
