import json\n\nfrom fastapi import APIRouter, Depends, HTTPException, Response, status
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.db import get_db
from app.models.diff import CompareResult, RegressionTestCase
from app.models.project import ProjectCreate, ProjectRead, ProjectScanRequest, StoredScanRead
from app.services.projects import (
    compare_latest, create_project, get_project, list_projects, list_scans, run_project_scan,
)

router = APIRouter(prefix="/api/v1/projects", tags=["projects"])

def _comparison_or_409(db: Session, project_id: int) -> CompareResult:
    if not get_project(db, project_id):
        raise HTTPException(status_code=404, detail="Project not found")
    result = compare_latest(db, project_id)
    if result is None:
        raise HTTPException(status_code=409, detail="Baseline and current scans are required")
    return result

def _markdown(tests: list[RegressionTestCase]) -> str:
    lines=["# AI Release Guardian — Regression Test Cases",""]
    for test in tests:
        lines += [f"## {test.id} — {test.title}",f"- Priority: {test.priority}",f"- Severity: {test.severity}",f"- Risk points: {test.risk_points}",f"- Locator: `{test.locator}`","","### Preconditions"]
        lines += [f"- {x}" for x in test.preconditions]
        lines += ["","### Steps"]+[f"{i}. {x}" for i,x in enumerate(test.steps,1)]
        lines += ["","### Expected results"]+[f"- {x}" for x in test.expected_results]+[""]
    return "\n".join(lines)

def _playwright(tests: list[RegressionTestCase]) -> str:
    lines=["import { test, expect } from '@playwright/test';","","// Generated by AI Release Guardian V2.","// Review TODO assertions before using this suite in CI.",""]
    for item in tests:
        title=json.dumps(f"{item.id} {item.title}")
        locator=json.dumps(item.locator)
        lines += [f"test({title}, async ({{ page }}) => {{","  // TODO: replace with the route/authentication required by this project.","  await page.goto('/');",f"  const target = page.locator({locator});","  await expect(target).toBeVisible();",f"  // Severity: {item.severity}; deterministic risk contribution: +{item.risk_points}.","  // TODO: encode the intended interaction and expected business outcome.","","});",""]
    return "\n".join(lines)

@router.post("", response_model=ProjectRead, status_code=status.HTTP_201_CREATED)
def create(data: ProjectCreate, db: Session = Depends(get_db)) -> ProjectRead:
    try:
        return create_project(db, data)
    except IntegrityError as exc:
        db.rollback()
        raise HTTPException(status_code=409, detail="Project name already exists") from exc

@router.get("", response_model=list[ProjectRead])
def all_projects(db: Session = Depends(get_db)) -> list[ProjectRead]:
    return list_projects(db)

@router.post("/{project_id}/scans", response_model=StoredScanRead, status_code=status.HTTP_201_CREATED)
async def scan(project_id: int, data: ProjectScanRequest, db: Session = Depends(get_db)) -> StoredScanRead:
    project = get_project(db, project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    return await run_project_scan(db, project, data)

@router.get("/{project_id}/scans", response_model=list[StoredScanRead])
def scans(project_id: int, db: Session = Depends(get_db)) -> list[StoredScanRead]:
    if not get_project(db, project_id):
        raise HTTPException(status_code=404, detail="Project not found")
    return list_scans(db, project_id)

@router.get("/{project_id}/regression-tests/export")
def export_regression_tests(project_id: int, format: str = "json", db: Session = Depends(get_db)) -> Response:
    result=_comparison_or_409(db, project_id)
    fmt=format.lower()
    if fmt=="json":
        body=json.dumps([x.model_dump() for x in result.regression_tests],indent=2)
        media_type="application/json"; filename="regression-tests.json"
    elif fmt=="markdown":
        body=_markdown(result.regression_tests)
        media_type="text/markdown"; filename="regression-tests.md"
    elif fmt=="playwright":
        body=_playwright(result.regression_tests)
        media_type="text/typescript"; filename="regression.generated.spec.ts"
    else:
        raise HTTPException(status_code=400, detail="format must be json, markdown, or playwright")
    return Response(content=body,media_type=media_type,headers={"Content-Disposition":f'attachment; filename="{filename}"'})

@router.get("/{project_id}/compare", response_model=CompareResult)
def compare(project_id: int, db: Session = Depends(get_db)) -> CompareResult:
    if not get_project(db, project_id):
        raise HTTPException(status_code=404, detail="Project not found")
    result = compare_latest(db, project_id)
    if result is None:
        raise HTTPException(status_code=409, detail="Baseline and current scans are required")
    return result
