import json

from fastapi import APIRouter, Depends, HTTPException, Response, status
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.db import get_db
from app.models.diff import CompareResult, ProjectReleaseOverview, RegressionTestCase, ReleaseGateResult
from app.models.project import ProjectCreate, ProjectRead, ProjectScanRequest, ReleasePolicy, StoredScanRead
from app.services.projects import (
    build_release_overview, compare_latest, create_project, get_project, latest_comparison_scans, list_projects, list_routes, list_scans, run_project_scan, update_release_policy,
)

router = APIRouter(prefix="/api/v1/projects", tags=["projects"])

def _comparison_or_409(db: Session, project_id: int, route: str | None = None) -> CompareResult:
    if not get_project(db, project_id):
        raise HTTPException(status_code=404, detail="Project not found")
    result = compare_latest(db, project_id, route)
    if result is None:
        raise HTTPException(status_code=409, detail="Baseline and current scans are required")
    return result

def _markdown(tests: list[RegressionTestCase]) -> str:
    lines=["# AI Release Guardian — Regression Test Cases",""]
    for test in tests:
        lines += [f"## {test.id} — {test.title}",f"- Priority: {test.priority}",f"- Severity: {test.severity}",f"- Risk points: {test.risk_points}",f"- Locator: `{test.locator}`","","### Preconditions"]
        lines += [f"- {x}" for x in test.preconditions]
        lines += ["","### Steps"]+[f"{i}. {x}" for i,x in enumerate(test.steps,1)]
        lines += ["","### Expected results"]+[f"- {x}" for x in test.expected_results]+[""]
    return "\n".join(lines)

def _js(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)

def _field_assertions(change) -> list[str]:
    lines: list[str] = []
    after = change.after
    for field in change.changed_fields:
        value = getattr(after, field)
        if field == "disabled":
            lines.append("  await expect(target).toBeDisabled();" if value else "  await expect(target).toBeEnabled();")
        elif field == "checked":
            lines.append("  await expect(target).toBeChecked();" if value else "  await expect(target).not.toBeChecked();")
        elif field == "required":
            lines.append(f"  await expect(target).toHaveJSProperty('required', {_js(bool(value)).lower()});")
        elif field == "readonly":
            lines.append(f"  await expect(target).toHaveJSProperty('readOnly', {_js(bool(value)).lower()});")
        elif field == "value":
            lines.append(f"  await expect(target).toHaveValue({_js(str(value))});")
        elif field == "text":
            lines.append(f"  await expect(target).toHaveText({_js(str(value))});")
        else:
            attributes = {
                "href": "href", "src": "src", "type": "type", "role": "role",
                "placeholder": "placeholder", "title": "title", "aria_label": "aria-label",
                "aria_describedby": "aria-describedby", "aria_expanded": "aria-expanded",
                "aria_checked": "aria-checked", "aria_selected": "aria-selected",
            }
            attr = attributes.get(field)
            if attr is not None:
                lines.append(f"  await expect(target).toHaveAttribute({_js(attr)}, {_js(str(value))});")
            else:
                lines.append(f"  // TODO: verify changed field {field} = {_js(value)}.")
    return lines

def _playwright(result: CompareResult, start_url: str = "/") -> str:
    tests = result.regression_tests
    changed_by_locator = {change.after.locator: change for change in result.diff.changed}
    removed = {item.locator for item in result.diff.removed}
    added = {item.locator for item in result.diff.added}

    lines = [
        "import { test, expect } from '@playwright/test';",
        "",
        "// Generated by AI Release Guardian V2.",
        "// Deterministic assertions are derived from the observed current DOM.",
        "// Review route/authentication and business-level expectations before CI use.",
        "",
    ]
    for item in tests:
        title = json.dumps(f"{item.id} {item.title}")
        locator = json.dumps(item.locator)
        lines += [
            f"test({title}, async ({{ page }}) => {{",
            f"  await page.goto({_js(start_url)});",
            f"  const target = page.locator({locator});",
        ]
        if item.locator in removed:
            lines.append("  await expect(target).toHaveCount(0);")
        else:
            lines.append("  await expect(target).toBeVisible();")
            change = changed_by_locator.get(item.locator)
            if change is not None:
                lines += _field_assertions(change)
            elif item.locator in added:
                lines.append("  // Added interactive element: verify its intended business behavior.")
        lines += [
            f"  // Severity: {item.severity}; deterministic risk contribution: +{item.risk_points}.",
            "  // TODO: add business-flow assertions that cannot be inferred from DOM state alone.",
            "",
            "});",
            "",
        ]
    return "\n".join(lines)

@router.post("", response_model=ProjectRead, status_code=status.HTTP_201_CREATED)
def create(data: ProjectCreate, db: Session = Depends(get_db)) -> ProjectRead:
    try:
        return create_project(db, data)
    except IntegrityError as exc:
        db.rollback()
        raise HTTPException(status_code=409, detail="Project name already exists") from exc

@router.get("", response_model=list[ProjectRead])
def all_projects(db: Session = Depends(get_db)) -> list[ProjectRead]:
    return list_projects(db)

@router.get("/{project_id}", response_model=ProjectRead)
def project(project_id: int, db: Session = Depends(get_db)) -> ProjectRead:
    found = get_project(db, project_id)
    if not found:
        raise HTTPException(status_code=404, detail="Project not found")
    return found

@router.put("/{project_id}/release-policy", response_model=ProjectRead)
def release_policy(project_id: int, data: ReleasePolicy, db: Session = Depends(get_db)) -> ProjectRead:
    project = get_project(db, project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    return update_release_policy(db, project, data)

@router.get("/{project_id}/release-gate", response_model=ReleaseGateResult)
def release_gate(project_id: int, db: Session = Depends(get_db)) -> ReleaseGateResult:
    if not get_project(db, project_id):
        raise HTTPException(status_code=404, detail="Project not found")
    overview = build_release_overview(db, project_id)
    allowed = overview.gate_status == "READY"
    return ReleaseGateResult(
        project_id=project_id,
        status=overview.gate_status,
        allowed=allowed,
        exit_code=0 if allowed else 1,
        reason=overview.gate_reason,
        overall_risk_score=overview.overall_risk_score,
        overall_risk_level=overview.overall_risk_level,
        comparable_routes=overview.comparable_routes,
        incomplete_routes=overview.incomplete_routes,
    )

@router.get("/{project_id}/release-overview", response_model=ProjectReleaseOverview)
def release_overview(project_id: int, db: Session = Depends(get_db)) -> ProjectReleaseOverview:
    if not get_project(db, project_id):
        raise HTTPException(status_code=404, detail="Project not found")
    return build_release_overview(db, project_id)

@router.get("/{project_id}/routes", response_model=list[str])
def routes(project_id: int, db: Session = Depends(get_db)) -> list[str]:
    if not get_project(db, project_id):
        raise HTTPException(status_code=404, detail="Project not found")
    return list_routes(db, project_id)

@router.post("/{project_id}/scans", response_model=StoredScanRead, status_code=status.HTTP_201_CREATED)
async def scan(project_id: int, data: ProjectScanRequest, db: Session = Depends(get_db)) -> StoredScanRead:
    project = get_project(db, project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    return await run_project_scan(db, project, data)

@router.get("/{project_id}/scans", response_model=list[StoredScanRead])
def scans(project_id: int, db: Session = Depends(get_db)) -> list[StoredScanRead]:
    if not get_project(db, project_id):
        raise HTTPException(status_code=404, detail="Project not found")
    return list_scans(db, project_id)

def _playwright_suite(db: Session, project_id: int) -> str:
    project = get_project(db, project_id)
    lines = [
        "import { test, expect } from '@playwright/test';",
        "",
        "// Generated by AI Release Guardian V2.",
        "// Multi-route deterministic regression suite.",
        "",
    ]
    for route in list_routes(db, project_id):
        result = compare_latest(db, project_id, route)
        if result is None:
            continue
        _, current_scan = latest_comparison_scans(db, project_id, route)
        start_url = current_scan.url if current_scan else (project.base_url if project and project.base_url else route)
        generated = _playwright(result, start_url).splitlines()
        body = generated[5:] if len(generated) > 5 else generated
        lines += [f"test.describe({_js(route)}, () => {{"]
        lines += [f"  {line}" if line else "" for line in body]
        lines += ["});", ""]
    return "\n".join(lines)

@router.get("/{project_id}/regression-tests/export")
def export_regression_tests(project_id: int, format: str = "json", route: str | None = None, db: Session = Depends(get_db)) -> Response:
    if not get_project(db, project_id):
        raise HTTPException(status_code=404, detail="Project not found")
    fmt=format.lower()
    if fmt=="playwright" and route is None:
        body=_playwright_suite(db, project_id)
        media_type="text/typescript"; filename="regression.multi-route.generated.spec.ts"
        return Response(content=body,media_type=media_type,headers={"Content-Disposition":f'attachment; filename="{filename}"'})
    result=_comparison_or_409(db, project_id, route)
    if fmt=="json":
        body=json.dumps([x.model_dump() for x in result.regression_tests],indent=2)
        media_type="application/json"; filename="regression-tests.json"
    elif fmt=="markdown":
        body=_markdown(result.regression_tests)
        media_type="text/markdown"; filename="regression-tests.md"
    elif fmt=="playwright":
        project=get_project(db, project_id)
        _, current_scan = latest_comparison_scans(db, project_id, route)
        start_url = current_scan.url if current_scan else (project.base_url if project and project.base_url else "/")
        body=_playwright(result, start_url)
        media_type="text/typescript"; filename="regression.generated.spec.ts"
    else:
        raise HTTPException(status_code=400, detail="format must be json, markdown, or playwright")
    return Response(content=body,media_type=media_type,headers={"Content-Disposition":f'attachment; filename="{filename}"'})

@router.get("/{project_id}/compare", response_model=CompareResult)
def compare(project_id: int, route: str | None = None, db: Session = Depends(get_db)) -> CompareResult:
    if not get_project(db, project_id):
        raise HTTPException(status_code=404, detail="Project not found")
    result = compare_latest(db, project_id, route)
    if result is None:
        raise HTTPException(status_code=409, detail="Baseline and current scans are required")
    return result
